#!/bin/bash
set -e -E -u -C -o pipefail

if [[ -d spring ]]; then
    (
    cd spring
    git pull --rebase || git pull
    git submodule sync
    git submodule update --init
    )
else
    # git clone --recursive https://github.com/spring/spring.git -b master
    git clone https://github.com/spring/spring.git -b master
    (
    cd spring
    git submodule sync
    git submodule update --init
    )
fi
if [[ -d tccai ]]; then
    (
    cd tccai
    git pull --rebase || git pull
    )
else
    git clone https://github.com/arnehilmann/tccai.git
fi

if [[ -d spring/AI/Skirmish/NullErlangAI ]]; then
    (
    cd spring/AI/Skirmish/NullErlangAI
    git pull --rebase || git pull
    )
else
    (
    cd spring/AI/Skirmish
    git clone https://github.com/arnehilmann/NullErlangAI.git
    )
fi

docker build -t arne/opengl --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy .
