#!/bin/bash
set -e -E -u -C -o pipefail

if [[ -d spring ]]; then
    (
    cd spring
    git pull --rebase || git pull
    git submodule sync
    git submodule update --init
    )
else
    # git clone --recursive https://github.com/spring/spring.git -b master
    git clone https://github.com/spring/spring.git -b master
    (
    cd spring
    git submodule sync
    git submodule update --init
    )
fi
if [[ -d tccai ]]; then
    (
    cd tccai
    git pull --rebase || git pull
    )
else
    git clone https://github.com/arnehilmann/tccai.git
fi

if [[ -d spring/AI/Skirmish/NullErlangAI ]]; then
    (
    cd spring/AI/Skirmish/NullErlangAI
    git pull --rebase || git pull
    )
else
    (
    cd spring/AI/Skirmish
    git clone https://github.com/arnehilmann/NullErlangAI.git
    )
fi

docker build -t arne/opengl --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy .

exit

git clone https://github.com/thewtex/docker-opengl.git

cat <<EOM

Follow the following steps now:

1. run 'docker-opengl/run.sh'

2. run 'docker exec -it opengl bash'
2a. set http(s) proxies if needed
2b. inside this docker container, cd to '/home/user/work/spring/AI/Skirmish/NullErlangAI'
2c. run './init'
2d. run './build'
2e. run './run'

3. run 'docker exec -it opengl bash'
3a.set http(s) proxies if needed
3b. inside this docker container, cd to '/home/user/work/tccai/'
3c. run './init'
3d. run './build'
3e. run './run'

4. point your browser to http://localhost:6080

EOM
